---
title: "Number of statements"
author: "Przemyslaw Biecek"
date: "17 February 2016"
output: 
  html_document:
    toc: TRUE
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(knitr)
library(archivist)
library(ggplot2)
library(sejmRP)
library(dplyr)
library(tidyr)
library(DT)

# options for chunks
opts_chunk$set(comment=NA, fig.width=6, fig.height=6, results='asis', warning=FALSE, message=FALSE, cache=FALSE)

# store everything in the archivist repo
addHooksToPrint(class="ggplot",
                 repoDir = "arepo", 
                 repo = "sejmRP", user = "mi2-warsaw", subdir = "UseCase/arepo")

```

Z jakich dat są debaty?

```{r, cache=FALSE, echo=FALSE}
allDep <- get_deputies_table()
allVotes <- get_filtered_votes(terms_of_office = c(8,8))
MCclubs <- sapply(unique(allVotes$surname_name), function(sn) {
  tmp <- allVotes[allVotes$surname_name == sn, ]
  names(tail(sort(table(tmp$club)), 1))
})

allStatements <- get_statements_table() %>% filter(nr_term_of_office == "8")

df <- data.frame(table(allStatements$date_statement))
colnames(df) = c("data", "liczba wypowiedzi")
datatable(df)

allStatements <- allStatements %>%
    mutate(surname_name=gsub(surname_name, pattern="Poseł Sprawozdawca ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Poseł ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Infrastruktury i Budownictwa ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Nauki i Szkolnictwa Wyższego ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Sprawiedliwości ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Edukacji Narodowej ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Finansów ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Spraw Zagranicznych ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Spraw Wewnętrznych i Administracji ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Rodziny, Pracy i Polityki Społecznej ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Energii ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Zdrowia ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Sekretarz ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Rolnictwa i Rozwoju Wsi ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Gospodarki Morskiej i Żeglugi Śródlądowej ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Minister Sportu i Turystyki ", replacement="")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Iwona Ewa Arent", replacement="Iwona Arent")) %>%
    mutate(surname_name=gsub(surname_name, pattern="Prezes Rady Ministrów ", replacement=""))

```

```{r, cache=FALSE, echo=FALSE}
getDepWithPatterns <- function(pattern, allStatements) {
  allStatements %>% 
    filter(grepl(titles_order_points, pattern=pattern)) %>%
    mutate(length = sapply(strsplit(statement, split=" +"), length)) %>%
    group_by(surname_name) %>%
    summarise(count=n(),
              sum = sum(length),
              statement = paste(statement, collapse="\n[NEXT]\n")) %>%
    mutate(pattern=ifelse(pattern=="", "wszystko", pattern)) %>%
    arrange(desc(sum), desc(count))
}
  
topics <- c("o służbie cywilnej", "w wychowywaniu dzieci", "o systemie oświaty", "o Policji", "o podatku od niektórych instytucji finansowych", "o radiofonii i telewizji", "o rządowym projekcie ustawy budżetowej", "polskiej polityki zagranicznej", "o Trybunale Konstytucyjnym", "Trybunału Konstytucyjnego", "")

results <- lapply(topics, getDepWithPatterns, allStatements=allStatements)
results <- do.call(rbind, results)
```

# Tabela z liczbą wystąpień per debata

```{r, echo=FALSE}
table <- results %>% 
  select(-statement, -sum) %>%
  spread(pattern, count, fill=0)

table <- table[order(-table[,ncol(table)]),]
#kable(as.data.frame(table))

kluby <- sapply(table$surname_name, function(sn) {
  nam1 <- strsplit(sn, split=" ")[[1]]
  wm <- sapply(names(MCclubs), function(mc) {
    nam2 <- strsplit(mc, split=" ")[[1]]
    length(intersect(nam1, nam2))
  }) 
  MCclubs[which.max(wm)]
})

table$kluby <- kluby
datatable(as.data.frame(table))
```

# Tabela z liczbą słow per debata

```{r, echo=FALSE}
table2 <- results %>% 
  select(-statement, -count) %>%
  spread(pattern, sum, fill=0)

table2 <- table[order(-table2[,ncol(table2)]),]
#kable(as.data.frame(table))

kluby <- sapply(table2$surname_name, function(sn) {
  nam1 <- strsplit(sn, split=" ")[[1]]
  wm <- sapply(names(MCclubs), function(mc) {
    nam2 <- strsplit(mc, split=" ")[[1]]
    length(intersect(nam1, nam2))
  }) 
  MCclubs[which.max(wm)]
})

table2$kluby <- kluby
datatable(as.data.frame(table2))

```

## Ile z mównicy ile z sali?

```{r, echo=FALSE, fig.width=12, fig.height=8}
# library(ggplot2)
# 
# table <- table[rowSums(table[,-1]) > 3,]
# 
# ggplot(results, aes(surname_name, y=count, fill=pattern)) +
#   geom_bar(stat = "identity") + 
#   coord_flip() + theme(legend.position="top")


wszystko <- paste(allStatements$statement, collapse = "\nNEXT")
wszystkoL <- strsplit(wszystko, split="(", fixed = TRUE)[[1]]
wszystkoL <- gsub(wszystkoL, pattern="\\).*$", replacement="")
wszystkoL <- grep(wszystkoL, pattern="^Poseł", value = TRUE)

didask <- data.frame(
  table(gsub(gsub(wszystkoL, 
          pattern="Poseł ", replacement=""), 
     pattern=":.*$", replacement="")))
colnames(didask) = c("surname_name", "wtracenia")

mer <- merge(table[,c("surname_name","wszystko")], didask, all=TRUE)
mer[is.na(mer[,3]),3]=0
mer[is.na(mer[,2]),2]=0

library(ggrepel)

kluby <- sapply(mer$surname_name, function(sn) {
  nam1 <- strsplit(sn, split=" ")[[1]]
  wm <- sapply(names(MCclubs), function(mc) {
    nam2 <- strsplit(mc, split=" ")[[1]]
    length(intersect(nam1, nam2))
  }) 
  MCclubs[which.max(wm)]
})

mer$kluby <- kluby
kolory <- c("black", "lightblue3", "grey80", "blue2", "orange3", "green4")

mer2 <- mer[mer$wtracenia > 70 | mer$wszystko > 25, ]
ggplot(mer2, aes(wtracenia, wszystko, color=kluby)) +
  geom_point(data=mer, size=4) +
  geom_text_repel(aes(label=surname_name)) +
  scale_color_manual(values=kolory) +
  xlab("Liczba wypowiedzi z sali") +
  ylab("Liczba wypowiedzi z mównicy") +
  theme_classic(base_size = 16)
```

```{r, echo=FALSE, fig.width=6, fig.height=6}
mer$kluby <- reorder(mer$kluby, mer$wszystko, mean)
ggplot(mer, aes(kluby, wszystko, fill=kluby, color=kluby)) +
  geom_boxplot(data=mer, alpha=0.3,coef=1000) +
  geom_point(data=mer, position=position_jitter(0.5,0)) +
  scale_color_manual(values=kolory[c(4,1,5,3,2,6)],guide = guide_legend(reverse=TRUE)) +
  scale_fill_manual(values=kolory[c(4,1,5,3,2,6)],guide = guide_legend(reverse=TRUE)) +
  ylab("Liczba wypowiedzi z mównicy (per poseł)") +
  xlab("")+
  theme_classic(base_size = 16)
  
mer$kluby <- reorder(mer$kluby, mer$wtracenia, mean)
ggplot(mer, aes(kluby, wtracenia, color=kluby, fill=kluby)) +
  geom_boxplot(data=mer, alpha=0.3,coef=1000) +
  geom_point(data=mer, position=position_jitter(0.5,0)) +
  scale_color_manual(values=kolory[c(3,1,2,6,4,5)],guide = guide_legend(reverse=TRUE)) +
  scale_fill_manual(values=kolory[c(3,1,2,6,4,5)],guide = guide_legend(reverse=TRUE)) +
  ylab("Liczba wypowiedzi z sali (oś sqrt)") +
  coord_trans(y="sqrt")+
  xlab("")+
  theme_classic(base_size = 16)
```

## Wtrącenia z sali

```{r, echo=FALSE}

getOff <- function(pattern, allStatements) {
  allStatements2 <- allStatements %>% 
    filter(grepl(titles_order_points, pattern=pattern))

  wszystko <- paste(allStatements2$statement, collapse = "\nNEXT")
  wszystkoL <- strsplit(wszystko, split="(", fixed = TRUE)[[1]]
  wszystkoL <- gsub(wszystkoL, pattern="\\).*$", replacement="")
  wszystkoL <- grep(wszystkoL, pattern="^Poseł", value = TRUE)

  didask <- data.frame(
  table(gsub(gsub(wszystkoL, 
          pattern="Poseł ", replacement=""), 
     pattern=":.*$", replacement="")))
  didask <- cbind(didask, topic=pattern)
  colnames(didask) = c("surname_name", "wtracenia", "debata")
  didask
}
  
results <- lapply(topics, getOff, allStatements=allStatements)
results <- do.call(rbind, results)
results$debata <- as.character(results$debata)
results$debata[results$debata == ""] <- "wszystko"

table3 <- results %>% 
  spread(debata, wtracenia, fill=0)

table3 <- table3[order(-table3[,ncol(table3)]),]
table3$surname_name <- as.character(table3$surname_name)

kluby <- sapply(table3$surname_name, function(sn) {
  nam1 <- strsplit(sn, split=" ")[[1]]
  wm <- sapply(names(MCclubs), function(mc) {
    nam2 <- strsplit(mc, split=" ")[[1]]
    length(intersect(nam1, nam2))
  }) 
  MCclubs[which.max(wm)]
})

table3$kluby <- kluby
datatable(as.data.frame(table3))

cat(paste((sort(wszystkoL)), collapse = "\n\n"))

```

## Kto komu przerywa

```{r, echo=FALSE}

getPre <- function(pattern, allStatements) {
  allStatements2 <- allStatements %>% 
    filter(grepl(surname_name, pattern=pattern))

  wszystko <- paste(allStatements2$statement, collapse = "\nNEXT")
  wszystkoL <- strsplit(wszystko, split="(", fixed = TRUE)[[1]]
  wszystkoL <- gsub(wszystkoL, pattern="\\).*$", replacement="")
  wszystkoL <- grep(wszystkoL, pattern="^Poseł", value = TRUE)

  didask <- data.frame(
  table(gsub(gsub(wszystkoL, 
          pattern="Poseł ", replacement=""), 
     pattern=":.*$", replacement="")))
  if (nrow(didask) == 0) return(NULL)
  didask <- cbind(didask, topic=pattern)
  colnames(didask) = c("komu", "ile", "kto")
  didask
}
  
results <- lapply(unique(allStatements$surname_name), 
                  getPre, allStatements=allStatements)
results <- do.call(rbind, results)
results$komu <- as.character(results$komu)
results$kto <- as.character(results$kto)

#results2 <- spread(results, surname_name, wtracenia, fill = 0)

kluby <- sapply(results$kto, function(sn) {
  nam1 <- strsplit(sn, split=" ")[[1]]
  wm <- sapply(names(MCclubs), function(mc) {
    nam2 <- strsplit(mc, split=" ")[[1]]
    length(intersect(nam1, nam2))
  }) 
  MCclubs[which.max(wm)]
})

findStatements <- function(kto, komu) {
  allStatements %>%
    filter(grepl(surname_name, pattern=komu)) %>%
    filter(grepl(statement, pattern=kto)) 
}
#findStatements("Krystyna Pawłowicz", "Stanisław Piotrowicz")
#findStatements("Magdalena Kochan", "Kornelia Wróblewska")

results$kto_klub <- kluby

kluby <- sapply(results$komu, function(sn) {
  nam1 <- strsplit(sn, split=" ")[[1]]
  wm <- sapply(names(MCclubs), function(mc) {
    nam2 <- strsplit(mc, split=" ")[[1]]
    length(intersect(nam1, nam2))
  }) 
  MCclubs[which.max(wm)]
})

results$komu_klub <- kluby

#write.csv(results, file = "przewania2.csv")

resultsAA <- results %>% 
  group_by(kto_klub, komu_klub) %>%
  summarise(sw = sum(ile)) %>%
  spread(komu_klub, sw, fill=0)

datatable(as.data.frame(resultsAA))

resultsAA <- as.data.frame(resultsAA)
rownames(resultsAA) <- resultsAA[,1]
resultsAA <- resultsAA[,-1]

library(ca)
plot(ca(resultsAA), mass = T, arrow=c(T,F))

```
